### ISSUE TITLE
create gem

### ISSUE THREAD

**Issue by langalex** [PayLane/paylane_ruby#1]
please create a gem and publish it so people don't have to copy&paste the code from here.

**Comment by PayLane** [comment]
This is something we are planning, however due to our current workload we have not been able to do so. It is in our backlog, though. This is planned for mid April.

**Comment by PayLane** [comment]
Since this is in our backlog, I am closing this issue.

**Comment by kozak** [comment]
Reopen ?

**Comment by UtamaruMonster** [comment]
Two years passed and no publish :(

**Comment by langalex** [comment]
@UtamaruMonster I saw the email about your comment from GitHub and got really excited that they finally did it, but no…

**Comment by UtamaruMonster** [comment]
Please reopen issue
